### ISSUE TITLE
Cannot rename additionalFields from MDC

### ISSUE THREAD

**Issue by BastianVoigt** [realityforge/gelf4j#13]
I want to output an MDC field "someFieldName" with the label "myFieldName" via gelf:

    MDC.put("someFieldName", "someValue")

So I tried to configure it as follows (tried both variants)

    <additionalFields>{"someFieldName":"myFieldName"}</additionalFields>

    <additionalFields>{"myFieldName":"someFieldName"}</additionalFields>

Intended behaviour: the field "myFieldName" should appear in gelf output 

Actual behaviour: The field is output as "someFieldName" for variant 1, and it is not output at all for variant 2.

**Comment by BastianVoigt** [comment]
Fixed in 1.9 :-)
Can you please update the maven snippet in your readme to point people to 1.9

**Comment by realityforge** [comment]
No problem - done.

Thanks for the heads up!
