### ISSUE TITLE
Logging stops after a few (ish) hours

### ISSUE THREAD

**Issue by Ryanmt2** [realityforge/gelf4j#14]
I have glassfish running with 2 apps deployed, both using gelf4j 1.9. One is low traffic one is high traffic, the low traffic one never fails however the high traffic one seems to cut out every few hours. Logs will not resume until the app is reloaded in glassfish or glassfish restarted.

Below is a copy of the domain server.log, the http-thread-pool message always seems to preceded the gelf error. Once this message is thrown nothing further is sent to my Graylog server from that app

```
[#|2016-01-20T18:26:01.963+0000|WARNING|glassfish3.1.1|com.sun.grizzly.config.GrizzlyServiceListener|_ThreadID=11;_ThreadName=Thread-2;|GRIZZLY0023: Interrupting idle Thread: http-thread-pool-8080(21).|#]
[#|2016-01-20T18:26:01.964+0000|SEVERE|glassfish3.1.1|javax.enterprise.system.std.com.sun.enterprise.server.logging|_ThreadID=46;_ThreadName=Thread-2;|log4j:ERROR Could not send GELF message|#]
```

At a loss how to debug this further since the cut out point looks random so far, any advice would be great.

My appender looks like this

```
<appender name="graylog2" class="gelf4j.log4j.GelfAppender">
    <param name="Threshold" value="DEBUG"/>
    <param name="host" value="my domain"/>
    <param name="compressedChunking" value="true"/>
    <param name="defaultFields" value='{ "environment": "Production", "application": "Interface"}'/>
    <param name="additionalFields" value='{"thread_name": "threadName", "exception": "exception"}'/>
</appender>
```

**Comment by realityforge** [comment]
Without investigating deeply, my suspicion is that there is a concurrency issue trigger on the datagram socket and when we unconditionally swallow the exception at

https://github.com/realityforge/gelf4j/blob/master/src/main/java/gelf4j/GelfConnection.java#L107

it is hidden. If you were to insert a close() in that block it may "fix" the issue by forcing a recreation of the socket. However it may be required that we mark the methods close(), getChannel() as synchronized

**Comment by realityforge** [comment]
I have added some code to do the above at https://github.com/realityforge/gelf4j/commit/e55b4afbb7c71cae300ed9a2193bfa19de032936 and I will try to release a version of gelf4j in the next few days

**Comment by realityforge** [comment]
I just released 1.10 to maven central. It should be up there in the next hour or so. If you could try that and see if it fixes the problem then that would be great.

**Comment by Ryanmt2** [comment]
Thanks for the quick fix!

I switched to gelfj as a trial to see is the problem continued, specifically after finding this which seems to indicate they fixed the same issue https://github.com/t0xa/gelfj/issues/87. After testing for a few days I haven't had any failures with gelfj

I will grab a copy now though ready for the next release and keep you updated. I may be a little while though since its a production env and deployments have to be scheduled in.

**Comment by Ryanmt2** [comment]
Forgot to update this one but the fix worked fine!
