### ISSUE TITLE
usage of MDC keys is not consistent with other fields

### ISSUE THREAD

**Issue by asaed** [realityforge/gelf4j#9]
First of all, this project is the best Gelf appender out there. Well done!

I've noticed a small inconsistency when using additional fields when it comes to MDC (i.e. Mapped Diagnostic Contexts). If I'm storing some data in the MDC as follows: 
```java
import org.slf4j.MDC;
...
MDC.put("user", "johnsmith123");
MDC.put("application.server", "tomcat");
```

Then the required log4j settings are (Notice that "user" and "application.server" has to be the key in the json object, while "threadName" and "exception" needs to be value not the key): 
```INI
log4j.appender.gelf.additionalFields={"thread": "threadName", "exception": "exception", "user": "", "application.server": "" }
```

And the resulting gelf message is: 
```javascript
{
"thread" : "Thread-6",
"user": "johnsmith123",
"application.server": "tomcat"
}
```

It becomes very confusing when I'm mixing MDC keys with other fields that this appender already supports. 

If we make MDC work the same way as "threadName" and "exception", we will have the added bonus of being able to customize the Gelf message keys. 

So what I'm suggesting is that if I have multiple applications sending logs to GrayLog and they all have "user" in their MDC, I can distinguish them as this: 
```INI
log4j.appender.gelf.additionalFields={"thread": "threadName", "exception": "exception", "coolAppUser": "user", "coolAppServer": "application.server" }
```

And the resulting Gelf message will be: 
```javascript
{
"thread" : "Thread-6",
"coolAppUser": "johnsmith123",
"coolAppServer": "tomcat"
}
```

**Comment by realityforge** [comment]
That's a great idea. I am currently on paternity leave and won't get a chance to hack on this for a while. But if you were to supply a pull request I would gladly merge it and release another version

**Comment by asaed** [comment]
The pull request is ready for you. Sorry for the delay but getting buildr to work on windows is just a nightmare.

**Comment by realityforge** [comment]
Great work. I will try to get a release out to Maven central in the next couple of days. 

Thanks again!
